const Product = require('../models/product');
const dotenv = require('dotenv');
const path = require('path');
const mongoose = require('mongoose');

// Sample product data -- to be replaced with actual products
// ONLY RUN ONCE! DO NOT RUN AFTER RUNNING WEAVIATE SYNC
const productSeeds = [
  {
    name: 'iPhone 15 Pro Max',
    description: "Apple's latest flagship smartphone.",
    price: 1099,
    category: 'electronics',
    image: 'https://cdn.tgdd.vn/Products/Images/42/305658/iphone-15-pro-max-blue-thumbnew-600x600.jpg',
    brand: 'Apple',
    stock: 100,
  },
  {
    name: 'MacBook Air M2',
    description: 'Powerful and lightweight laptop from Apple.',
    price: 1199,
    category: 'computers',
    image: 'https://cdn8.web4s.vn/media/products/mac-air-m2/macbookairm2-midnight%201.jpg',
    brand: 'Apple',
    stock: 50,
  },
  {
    name: 'MacBook Pro 14" M2 Pro',
    description: 'High-performance laptop with M2 Pro chip.',
    price: 1999,
    category: 'computers',
    image:
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/refurb-mbp14-m2-silver-202303?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=ZmdRZFZQaThmdmpsRzMrNlU0TnIrNVN1UEFsa2dENVBwbUVOOUlVZ3dMdmRxTENLaEJiU0o5a1FqaDFsUHhYNjE1UUxLT2t0cW42N3FvQzVqaGhrVVltRElNTjY0QXJtekNDMXFQT2xOSU4rYWpGdS9XeFgvbS9ITnNYOEhYaG4',
    brand: 'Apple',
    stock: 30,
  },
  {
    name: 'Sony WH-1000XM5 Headphones',
    description: 'Industry-leading noise-canceling headphones.',
    price: 399,
    category: 'electronics',
    image: 'https://bizweb.dktcdn.net/100/340/129/products/wh1000xm5-midnightblue-2-cuongphanvn.jpg?v=1714306049613',
    brand: 'Sony',
    stock: 200,
  },
  {
    name: 'Samsung 65" QLED TV',
    description: 'Immersive 4K TV experience with QLED technology.',
    price: 1499,
    category: 'electronics',
    image: 'https://cdn.mediamart.vn/images/product/qled-tivi-4k-samsung-65-inch-65q80c-smart-tv_5304e716.png', // Replace with actual image URL
    brand: 'Samsung',
    stock: 10,
  },
  {
    name: 'Canon EOS R5',
    description: 'High-performance mirrorless camera from Canon.',
    price: 3799,
    category: 'electronics',
    image: 'https://i1.adis.ws/i/canon/eos-r5_front_rf24-105mmf4lisusm_square_32c26ad194234d42b3cd9e582a21c99b',
    brand: 'Canon',
    stock: 5,
  },
  {
    name: 'Apple Watch Series 7',
    description: 'Stay connected and healthy with the latest Apple Watch.',
    price: 399,
    category: 'electronics',
    image: 'https://akbroshop.com/wp-content/uploads/2022/08/hinh-aw-s7-xanh.jpg',
    brand: 'Apple',
    stock: 100,
  },
  {
    name: 'Dell XPS 15',
    description: 'Powerful laptop with stunning 4K display.',
    price: 1799,
    category: 'computers',
    image: 'https://astringo-rugged.com/wp-content/uploads/2021/12/XPS-9510a.jpg',
    brand: 'Dell',
    stock: 20,
  },
  {
    name: 'Samsung Galaxy Tab S7+',
    description: 'Premium Android tablet with stunning AMOLED display.',
    price: 849,
    category: 'electronics',
    image: 'https://hanoicomputercdn.com/media/product/60370_may_tinh_bang_samsung_galaxy_tab_s7_plus_128gb_den.png',
    brand: 'Samsung',
    stock: 30,
  },
  {
    name: 'Sony A7 IV',
    description: 'Full-frame mirrorless camera with 33MP sensor.',
    price: 2499,
    category: 'electronics',
    image: 'https://zshop.vn/images/detailed/92/1634812545_1667800.jpg',
    brand: 'Sony',
    stock: 10,
  },
  {
    name: 'LG C1 OLED TV',
    description: 'Stunning OLED TV with great picture quality.',
    price: 1999,
    category: 'electronics',
    image: 'https://product.hstatic.net/200000574527/product/dz-6_ac9672a6534245fcbb1a4938a1337907_1024x1024.jpg',
    brand: 'LG',
    stock: 15,
  },
  {
    name: 'Microsoft Surface Laptop 4',
    description: 'Sleek and powerful laptop from Microsoft.',
    price: 1299,
    category: 'computers',
    image: 'https://m.media-amazon.com/images/I/617for1TmjL.jpg',
    brand: 'Microsoft',
    stock: 25,
  },
  {
    name: 'GoPro Hero 10 Black',
    description: 'High-performance action camera for capturing your adventures.',
    price: 499,
    category: 'electronics',
    image: 'https://cdn.vjshop.vn/camera-hanh-dong/gopro/gopro-hero-10/gopro-hero-10-1000x1000.png',
    brand: 'GoPro',
    stock: 50,
  },
  {
    name: 'Bose QuietComfort 45 Headphones',
    description: 'Premium noise-canceling headphones for immersive audio experience.',
    price: 329,
    category: 'electronics',
    image: 'https://cdn.nguyenkimmall.com/images/detailed/848/10054167-tai-nghe-khong-day-bose-quietcomfort-45-den-866724-0100-1.jpg',
    brand: 'Bose',
    stock: 100,
  },
  {
    name: 'iPad Pro 12.9" (2022)',
    description: 'Powerful tablet with M1 chip and stunning Liquid Retina XDR display.',
    price: 1099,
    category: 'electronics',
    image: 'https://cdn2.cellphones.com.vn/x/media/catalog/product/i/p/ipad-pro-13-select-202210_3_3_1_1.png',
    brand: 'Apple',
    stock: 50,
  },
  {
    name: 'Samsung Galaxy S22 Ultra',
    description: "Samsung's latest flagship smartphone with S Pen support.",
    price: 1199,
    category: 'electronics',
    image:
      'https://i5.walmartimages.com/seo/Samsung-Galaxy-S22-Ultra-5G-SM-S908U1-256GB-Green-US-Model-Factory-Unlocked-Cell-Phone-Very-Good-Condition_0b4b7166-2688-4e0c-954d-539d5ea29ad9.5946110fe2a2c21cda0b256e2969a555.jpeg',
    brand: 'Samsung',
    stock: 30,
  },
  {
    name: 'Sony A7C',
    description: 'Compact full-frame mirrorless camera with 24MP sensor.',
    price: 1799,
    category: 'electronics',
    image: 'https://cdn.vjshop.vn/may-anh/mirrorless/sony/sony-alpha-a7c/sony-a7c-black-1.jpg',
    brand: 'Sony',
    stock: 10,
  },
  {
    name: 'LG Gram 17" Laptop',
    description: 'Ultra-lightweight laptop with long battery life.',
    price: 1499,
    category: 'computers',
    image: 'https://lapvip.vn/upload/products/original/lg-gram-17-20232-1700187329.jpg',
    brand: 'LG',
    stock: 20,
  },
  {
    name: 'Canon EOS R6',
    description: 'High-performance mirrorless camera with 20MP sensor.',
    price: 2499,
    category: 'electronics',
    image: 'https://cdn.vjshop.vn/may-anh/mirrorless/canon/canon-eos-r6/canon-eos-r6-1-1500x1500.jpg',
    brand: 'Canon',
    stock: 5,
  },
  {
    name: 'Apple AirPods Max',
    description: 'Premium over-ear headphones with high-fidelity audio.',
    price: 549,
    category: 'electronics',
    image:
      'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/airpods-max-hero-select-202011_FMT_WHH?wid=607&hei=556&fmt=jpeg&qlt=90&.v=1633623988000',
    brand: 'Apple',
    stock: 50,
  },
  {
    name: 'Dell XPS 13',
    description: 'Ultra-portable laptop with stunning InfinityEdge display.',
    price: 999,
    category: 'computers',
    image: 'https://product.hstatic.net/1000331874/product/dell_xps_13_dc9a366cc90c495b9a3da844f2a08cb9_1024x1024.jpg',
    brand: 'Dell',
    stock: 30,
  },
  {
    name: 'Samsung Galaxy Watch 4',
    description: 'Stylish smartwatch with advanced health tracking features.',
    price: 249,
    category: 'electronics',
    image: 'https://cdn-v2.didongviet.vn/files/media/catalog/product/s/a/samsung-galaxy-watch-4-40mm-likenew-mau-den-didongviet.jpeg',
    brand: 'Samsung',
    stock: 100,
  },
  {
    name: 'Sony WH-1000XM4 Headphones',
    description: 'Premium noise-canceling headphones with long battery life.',
    price: 349,
    category: 'electronics',
    image: 'https://www.sony.com.vn/image/5d02da5df552836db894cead8a68f5f3?fmt=pjpeg&wid=330&bgcolor=FFFFFF&bgc=FFFFFF',
    brand: 'Sony',
    stock: 100,
  },
  {
    name: 'Microsoft Surface Pro 8',
    description: 'Versatile 2-in-1 laptop with high-resolution touchscreen.',
    price: 1099,
    category: 'computers',
    image:
      'https://i5.walmartimages.com/seo/Microsoft-Surface-Pro-8-13-2880x1920-i5-1135G7-8-256GB-SSD-GRAPHITE_2420c241-6f5d-414e-8ea7-9fd21f5c738e.a52cad9a8bb4e28eea851090f3df36c3.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF',
    brand: 'Microsoft',
    stock: 25,
  },
  {
    name: 'GoPro Hero 9 Black',
    description: 'Action camera with advanced stabilization and 5K video.',
    price: 399,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/513QgYmBUrL._UF894,1000_QL80_.jpg',
    brand: 'GoPro',
    stock: 50,
  },
  {
    name: 'Bose Noise Cancelling Headphones 700',
    description: 'Premium headphones with adaptive noise cancellation.',
    price: 379,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/51ovuAC+fML._UF894,1000_QL80_.jpg',
    brand: 'Bose',
    stock: 100,
  },
  {
    name: 'iPad Air (2022)',
    description: 'Powerful tablet with M1 chip and Liquid Retina display.',
    price: 599,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/61j3ZmlDciL.jpg',
    brand: 'Apple',
    stock: 50,
  },
  {
    name: 'Samsung Galaxy Z Fold3',
    description: 'Innovative foldable smartphone with S Pen support.',
    price: 1799,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/71MFE2UY6-L._UF894,1000_QL80_.jpg',
    brand: 'Samsung',
    stock: 30,
  },
  {
    name: 'Sony A6600',
    description: 'Compact mirrorless camera with 24MP sensor and fast autofocus.',
    price: 1399,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/71S46KIWZSL._UF894,1000_QL80_.jpg',
    brand: 'Sony',
    stock: 10,
  },
  {
    name: 'LG OLED C1 Series TV',
    description: 'Stunning OLED TV with Dolby Vision and Dolby Atmos support.',
    price: 1999,
    category: 'electronics',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOCLMqp7pz0tLjKm2tCeJOeJ2EJ5Y5kkmf2w&s',
    brand: 'LG',
    stock: 15,
  },
  {
    name: 'Dell Inspiron 15 Laptop',
    description: 'Affordable laptop with great performance for everyday tasks.',
    price: 699,
    category: 'computers',
    image: 'https://m.media-amazon.com/images/I/51OQ4248r-L._UF894,1000_QL80_.jpg',
    brand: 'Dell',
    stock: 20,
  },
  {
    name: 'Apple Mac Mini (M1, 2020)',
    description: 'Compact desktop computer with M1 chip for powerful performance.',
    price: 699,
    category: 'computers',
    image: 'https://m.media-amazon.com/images/I/71pcTYT+ICL._UF894,1000_QL80_.jpg',
    brand: 'Apple',
    stock: 25,
  },
  {
    name: 'Samsung Galaxy Buds Pro',
    description: 'Premium true wireless earbuds with active noise cancellation.',
    price: 199,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/51c8jaXEp+S.jpg',
    brand: 'Samsung',
    stock: 100,
  },
  {
    name: 'Sony WH-CH710N Headphones',
    description: 'Affordable noise-canceling headphones with long battery life.',
    price: 199,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/51VQwL2+wuL._UF894,1000_QL80_.jpg',
    brand: 'Sony',
    stock: 100,
  },
  {
    name: 'Microsoft Surface Laptop Go',
    description: 'Compact and affordable laptop with great performance.',
    price: 699,
    category: 'computers',
    image: 'https://cdn-dynmedia-1.microsoft.com/is/image/microsoftcorp/FL2C-A-BB-00?qlt=90&wid=1253&hei=705&extendN=0.12,0.12,0.12,0.12&bgc=FFFFFFFF&fmt=jpg',
    brand: 'Microsoft',
    stock: 25,
  },
  {
    name: 'GoPro Hero 8 Black',
    description: 'Action camera with HyperSmooth stabilization and 4K video.',
    price: 299,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/61oRRIabmZL.jpg',
    brand: 'GoPro',
    stock: 50,
  },
  {
    name: 'Bose SoundLink Revolve+ Bluetooth Speaker',
    description: 'Portable Bluetooth speaker with 360-degree sound.',
    price: 299,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/61mkO-GAIaL.jpg',
    brand: 'Bose',
    stock: 100,
  },
  {
    name: 'iPad Mini (2021)',
    description: 'Compact tablet with A15 Bionic chip and Liquid Retina display.',
    price: 499,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/71wEKxQlZkL.jpg',
    brand: 'Apple',
    stock: 50,
  },
  {
    name: 'Samsung Galaxy Z Flip3',
    description: 'Innovative foldable smartphone with compact design.',
    price: 999,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/61gELRjp5NL._UF894,1000_QL80_.jpg',
    brand: 'Samsung',
    stock: 30,
  },
  {
    name: 'Sony A7R IV',
    description: 'High-resolution full-frame mirrorless camera with 61MP sensor.',
    price: 3499,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/71qre0hvi6L.jpg',
    brand: 'Sony',
    stock: 10,
  },
  {
    name: 'LG Gram 14" Laptop',
    description: 'Ultra-lightweight laptop with long battery life.',
    price: 1299,
    category: 'computers',
    image: 'https://m.media-amazon.com/images/I/71Y8Jwu4DHL._UF894,1000_QL80_.jpg',
    brand: 'LG',
    stock: 20,
  },
  {
    name: 'Canon EOS M50 Mark II',
    description: 'Compact mirrorless camera with 24MP sensor and Dual Pixel autofocus.',
    price: 699,
    category: 'electronics',
    image:
      'https://cdn.media.amplience.net/i/canon/eos-m50-mark-ii-black-the-front-m15-45_gallery-images_04_06baea4af09f4197afef103303f8ffac?$prod-gallery-1by1-jpg$',
    brand: 'Canon',
    stock: 5,
  },
  {
    name: 'Apple AirPods Pro (2nd Gen)',
    description: 'Premium true wireless earbuds with active noise cancellation.',
    price: 249,
    category: 'electronics',
    image:
      'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/airpods-pro-2-hero-select-202409_FMT_WHH?wid=750&hei=556&fmt=jpeg&qlt=90&.v=1724041668836',
    brand: 'Apple',
    stock: 50,
  },
  {
    name: 'Dell XPS 17 Laptop',
    description: 'Powerful laptop with stunning 4K display and dedicated graphics.',
    price: 1999,
    category: 'computers',
    image: 'https://m.media-amazon.com/images/I/81S-yXzvFPL.jpg',
    brand: 'Dell',
    stock: 30,
  },
  {
    name: 'Samsung Galaxy Watch Active2',
    description: 'Stylish smartwatch with fitness tracking features.',
    price: 249,
    category: 'electronics',
    image: 'https://image-us.samsung.com/SamsungUS/home/mobile/wearables/pdp/sm-r820nzkaxar/Gallery-Active2-BT-44mm-AquaBlack-1.jpg',
    brand: 'Samsung',
    stock: 100,
  },
  {
    name: 'Sony WH-XB900N Headphones',
    description: 'Affordable noise-canceling headphones with extra bass.',
    price: 249,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/I/51VlRUpPWqL._UF894,1000_QL80_.jpg',
    brand: 'Sony',
    stock: 100,
  },
  {
    name: 'Microsoft Surface Pro X',
    description: 'Sleek 2-in-1 laptop with ARM processor and LTE connectivity.',
    price: 999,
    category: 'computers',
    image: 'https://m.media-amazon.com/images/I/71cEgrftILL.jpg',
    brand: 'Microsoft',
    stock: 25,
  },
  {
    name: 'DJI Mavic Air 2',
    description: 'Compact drone with 4K video and intelligent shooting modes.',
    price: 799,
    category: 'electronics',
    image: 'https://se-cdn.djiits.com/tpc/uploads/carousel/image/36686a09675382bfb57d7d12a3a1165f@ultra.jpg',
    brand: 'DJI',
    stock: 50,
  },
  {
    name: 'Bose SoundSport Free Wireless Earbuds',
    description: 'True wireless earbuds with great sound and comfort.',
    price: 199,
    category: 'electronics',
    image: 'https://m.media-amazon.com/images/S/aplus-media/sota/6fb5cb83-8f6c-40e0-b439-7090e75a0bd2._CR0,0,800,600_PT0_SX800__.jpg',
    brand: 'Bose',
    stock: 100,
  },
  {
    name: 'DJI Osmo Pocket 2',
    description: 'Compact handheld gimbal camera with 4K video.',
    price: 349,
    category: 'electronics',
    image: 'https://se-cdn.djiits.com/tpc/uploads/carousel/image/8882692311e107b9f4f490d774ca43eb@ultra.jpg',
    brand: 'DJI',
    stock: 50,
  },
  {
    name: 'Apple MacBook Pro 16" (2021)',
    description: 'Powerful laptop with M1 Pro chip and stunning Liquid Retina XDR display.',
    price: 2499,
    category: 'computers',
    image: 'https://m.media-amazon.com/images/I/615Ovlhw+XL.jpg',
    brand: 'Apple',
    stock: 25,
  },
  {
    name: 'Dell Alienware m15 R6 Gaming Laptop',
    description: 'High-performance gaming laptop with NVIDIA GeForce RTX 3060.',
    price: 1799,
    category: 'computers',
    image: 'https://m.media-amazon.com/images/I/71J1lHBTo3L._UF894,1000_QL80_.jpg',
    brand: 'Dell',
    stock: 20,
  },
];

const seedDB = async () => {
  await Product.deleteMany({});
  await Product.insertMany(productSeeds);
  console.log('Products data seeded successfully!');
};

// Only runs when the "node productSeeds.js dev" command is executed manually
if (process.argv[2] == 'dev') {
  dotenv.config({ path: path.resolve(__dirname, '../.env') });
  mongoose.connect(process.env.MONGO_URI, {}).then(async () => {
    await seedDB();
    process.exit();
  });
}

module.exports = seedDB;
